version: "3.9"

services:
  pg_sugar:
    container_name: "pg_sugar"
    image: "postgres"
    restart: "always"
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "25432:5432"